import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";

export default async function CampaignPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ submitted?: string }> }) {
  const { slug } = await params;
  const sp = await searchParams;
  const campaign = await prisma.campaign.findUnique({ where: { slug }, include: { project: true, tasks: true, proofSubmissions: true } });
  if (!campaign || campaign.status !== "published") notFound();
  return <section className="container-shell grid gap-6 py-12 lg:grid-cols-[1fr_380px]"><article className="glass rounded-[34px] p-8"><p className="text-sm font-black uppercase tracking-[0.24em] text-moss">{campaign.campaignType} campaign</p><h1 className="mt-3 text-5xl font-black md:text-7xl">{campaign.title}</h1><p className="mt-4 rounded-2xl bg-amber-100 p-4 text-sm font-bold text-amber-950">Sponsored disclosure: this is a reviewed campaign. It does not guarantee stars, rewards, airdrops, or acceptance.</p><p className="mt-6 text-lg leading-8 text-ink/68">{campaign.brief}</p><div className="mt-8 grid gap-3 md:grid-cols-2"><Fact label="Project" value={campaign.project.name} /><Fact label="Reward" value={campaign.rewardDescription ?? "Manual-first"} /><Fact label="Eligibility" value={campaign.eligibility ?? "See brief"} /><Fact label="Budget" value={campaign.budgetLabel ?? "Undisclosed"} /></div><h2 className="mt-10 text-3xl font-black">Tasks</h2><div className="mt-4 grid gap-3">{campaign.tasks.map((task) => <div key={task.id} className="rounded-2xl bg-white/50 p-4"><p className="font-black">{task.title}</p><p className="mt-1 text-sm text-ink/60">Proof: {task.proofRequirements}</p></div>)}</div></article><aside className="glass h-fit rounded-[30px] p-6"><h2 className="text-2xl font-black">Submit proof</h2>{sp.submitted ? <p className="mt-3 rounded-2xl bg-emerald-100 p-3 text-sm font-bold text-emerald-900">Proof received for review.</p> : null}<form action={`/api/campaigns/${campaign.slug}/proof`} method="post" className="mt-4 grid gap-3"><select name="taskId" className="rounded-2xl bg-white/70 px-3 py-3"><option value="">General proof</option>{campaign.tasks.map((task) => <option key={task.id} value={task.id}>{task.title}</option>)}</select><input name="email" type="email" placeholder="email if not logged in" className="rounded-2xl bg-white/70 px-3 py-3" /><input name="proofUrl" type="url" required placeholder="https://proof.example" className="rounded-2xl bg-white/70 px-3 py-3" /><textarea name="note" placeholder="What did you build or explain?" className="rounded-2xl bg-white/70 px-3 py-3" rows={4} /><button className="rounded-full bg-ink px-5 py-3 font-black text-sand">Submit for quality review</button></form></aside></section>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white/50 p-4"><p className="text-sm text-ink/50">{label}</p><p className="mt-1 font-black">{value}</p></div>; }
