import { requireAdmin } from "@/lib/admin";
import { prisma } from "@/lib/prisma";

export default async function AdminCampaignsPage() {
  await requireAdmin();
  const [campaigns, projects] = await Promise.all([
    prisma.campaign.findMany({ include: { project: true, tasks: true, proofSubmissions: true }, orderBy: { createdAt: "desc" } }),
    prisma.project.findMany({ where: { status: "published" }, orderBy: { name: "asc" }, take: 100 }),
  ]);
  return <section className="container-shell grid gap-6 pb-16 lg:grid-cols-[380px_1fr]"><form action="/api/admin/campaigns" method="post" className="glass rounded-[30px] p-6 lg:sticky lg:top-28 lg:self-start"><h1 className="text-3xl font-black">Create campaign</h1><label className="mt-4 block"><span className="text-sm font-black">Project</span><select name="projectId" required className="mt-1 w-full rounded-2xl bg-white/70 px-3 py-2">{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><Field name="title" label="Title" required /><Select name="campaignType" label="Type" options={["mindshare", "buildshare", "usageshare", "creatorshare", "referralshare"]} /><Field name="rewardDescription" label="Reward description" /><Field name="eligibility" label="Eligibility" /><Field name="budgetLabel" label="Budget label" /><label className="mt-3 block"><span className="text-sm font-black">Brief</span><textarea name="brief" required rows={5} className="mt-1 w-full rounded-2xl bg-white/70 px-3 py-2" /></label><Field name="taskTitle" label="First task title" /><Field name="proofRequirements" label="Proof requirements" /><button className="mt-4 rounded-full bg-ink px-5 py-3 font-black text-sand">Create draft</button></form><div><h1 className="mb-5 text-5xl font-black">Campaigns</h1><div className="grid gap-4">{campaigns.map((campaign) => <article key={campaign.id} className="glass rounded-[28px] p-5"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="text-xl font-black">{campaign.title}</p><p className="mt-1 text-sm text-ink/60">{campaign.project.name} / {campaign.campaignType} / {campaign.status} / sponsored={String(campaign.isSponsored)}</p><p className="mt-2 text-sm text-ink/60">{campaign.tasks.length} tasks / {campaign.proofSubmissions.length} proofs</p></div>{campaign.status !== "published" ? <form action={`/api/admin/campaigns/${campaign.id}/publish`} method="post"><button className="rounded-full bg-moss px-4 py-2 text-sm font-black text-white">Publish</button></form> : null}</div></article>)}</div></div></section>;
}
function Field({ name, label, required }: { name: string; label: string; required?: boolean }) { return <label className="mt-3 block"><span className="text-sm font-black">{label}</span><input name={name} required={required} className="mt-1 w-full rounded-2xl bg-white/70 px-3 py-2" /></label>; }
function Select({ name, label, options }: { name: string; label: string; options: string[] }) { return <label className="mt-3 block"><span className="text-sm font-black">{label}</span><select name={name} className="mt-1 w-full rounded-2xl bg-white/70 px-3 py-2">{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }
